Feature version mobile
LuisFerRG/Proyect-Landing-Page-1 pull request #2
Opened 2023-11-07 00:46 UTC by LuisFerRG

2023-11-19 12:42 UTC, Edjhernandez requested changes
Congrats @LuisFerRG !!!
you did a very good job, please check my comments...
Keep coding both!

<img src="https://media1.giphy.com/media/WGpR51t9qb79SNFOts/giphy.gif"/>

2023-11-19 12:42 UTC, Edjhernandez commented on index.html
> +        <h1><br>got marketing?<br>
Good job @LuisFerRG!!! 
In line 16, I suggest,  you can use <br> tag just at the end of the line where you want to force line breaks.

2023-11-19 12:42 UTC, Edjhernandez commented on index.html
> +        <h3>Email</h3>
In this case, lines 24 and 29, as part of a form these tags have the same importance level, I suggest that using the same tag.

2023-11-19 12:42 UTC, Edjhernandez commented on index.html
> +        <h3>Email</h3>
or label tag, you could investigate that.

2023-11-19 12:42 UTC, Edjhernandez commented on styles.css
> +.fish-hook1 > input[type="name"] {
Remember DRY, you can use some selectors that have the same rules.
lines 73-79 and 93-99 have the same properties.

.fish-hook1 > input[type="name"],
.fish-hook2 > input[type="email"] {
   properties in common
}

2023-11-19 12:42 UTC, Edjhernandez commented on styles.css
> +  max-width: 100%;
I suggest using 'px 'to fixed max-min

2023-11-19 12:42 UTC, Edjhernandez commented on styles.css
> +  max-height: 576px;
like this, great job...

2023-11-19 12:42 UTC, Edjhernandez commented on styles.css
> +  padding: 0 3%;
i suggest to investigate how units of % works with padding and marging

2023-11-19 12:42 UTC, Edjhernandez commented on styles.css
> +
From here, designs for other screens are included, but this PR says it is mobile only...

I suggest that you keep each screen design in different branches...

2023-11-22 23:13 UTC, LuisFerRG commented
Mobile screen 

![image](https://github.com/LuisFerRG/Proyect-Landing-Page-1/assets/135682291/6aa8c649-2e33-4b3b-a581-2e3ed97e6f03)

2023-11-22 23:15 UTC, merged